version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - database

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: