apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: m1dnightsp/backend:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env:
          - name: KC_ADMIN_CLIENT_ID
            value: "backend-admin"
          - name: KC_ADMIN_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: KC_ADMIN_SECRET
          - name: KEYCLOAK_BASE_URL
            value: "http://keycloak:8080"
          - name: KEYCLOAK_REALM
            value: "projekt"
          # możesz zostawić KEYCLOAK_ISSUER na 127.0.0.1 (to co masz w „iss” tokena),
          # albo w ogóle go nie używać w kodzie
          - name: KEYCLOAK_ISSUER
            value: "http://127.0.0.1/realms/projekt"
          - name: KEYCLOAK_AUDIENCE
            value: "frontend"
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: DB_PASSWORD

        # healthchecks
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

        # zoptymalizowane zasoby
        resources:
          requests:
            cpu:    "100m"
            memory: "128Mi"
          limits:
            cpu:    "250m"
            memory: "256Mi"