apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
data:
  realm.json: |
    {
      "id": "projekt",
      "realm": "projekt",
      "displayName": "Projekt",
      "enabled": true,
      "clients": [
        {
          "clientId": "frontend",
          "enabled": true,
          "publicClient": true,
          "redirectUris": ["http://127.0.0.1/*"],
          "protocol": "openid-connect"
        }
      ],
      "users": [
        {
          "username": "admin",
          "enabled": true,
          "credentials": [
            { "type": "password", "value": "admin" }
          ]
        }
      ]
    }