apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
data:
  realm.json: |
    {
      "id": "projekt",
      "realm": "projekt",
      "enabled": true,
      "clients": [
        {
          "clientId": "frontend",
          "publicClient": true,
          "enabled": true,
          "directAccessGrantsEnabled": false,
          "standardFlowEnabled": true,
          "redirectUris": ["http://127.0.0.1/*"],
          "protocol": "openid-connect"
        },
        {
          "clientId": "backend-admin",
          "publicClient": false,
          "enabled": true,
          "secret": "Zm9vYmFyMTIzIT8=",
          "serviceAccountsEnabled": true,
          "directAccessGrantsEnabled": false,
          "standardFlowEnabled": false,
          "protocol": "openid-connect"
        }
      ],
      "users": [
        {
          "username": "admin",
          "enabled": true,
          "credentials": [
            { "type": "password", "value": "admin" }
          ]
        }
      ]
    }