name: Build & Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU (multi‐arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push frontend image
        uses: docker/build-push-action@v4
        with:
          context: frontend
          file: frontend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Build & push backend image
        uses: docker/build-push-action@v4
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Build & push database image
        uses: docker/build-push-action@v4
        with:
          context: database
          file: database/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/database:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/database:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - run: |
          kubectl set image deployment/frontend frontend=${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
          kubectl set image deployment/backend  backend=${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
          kubectl set image deployment/postgres postgres=${{ secrets.DOCKERHUB_USERNAME }}/database:${{ github.sha }}
          kubectl rollout status deployment/frontend
          kubectl rollout status deployment/backend
          kubectl rollout status deployment/postgres